version: '3.8'

services:
  backend:
    build: ./backend
    ports:
     - "8000:8000"
    networks:
      - scraper_network

  scraper:
    build: ./scraper
    container_name: scraper
    ports:
      - "6800:6800"
    networks:
      - scraper_network
    environment:
      - MONGO_API_USER=${MONGO_API_USER}
      - MONGO_API_PASS=${MONGO_API_PASS}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=${MONGO_DB}
      - MONGO_COLLECTION_KITAPYURDU=${MONGO_COLLECTION_KITAPYURDU}  
      - MONGO_COLLECTION_KITAPSEPETI=${MONGO_COLLECTION_KITAPSEPETI}

  mongodb:
    image: mongo:4.2.3-bionic
    container_name: mongodb
    ports:
      - 27017:27017
    networks:
      - scraper_network
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_API_USER=${MONGO_API_USER}
      - MONGO_API_PASS=${MONGO_API_PASS}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=${MONGO_DB}
      - MONGO_COLLECTION_KITAPYURDU=${MONGO_COLLECTION_KITAPYURDU}  
      - MONGO_COLLECTION_KITAPSEPETI=${MONGO_COLLECTION_KITAPSEPETI}  
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro

networks:
  scraper_network:
    name: scraper_network